out_dir: results
metric_best: accuracy
wandb:
  use: True
  project: molpcba
dataset:
  format: OGB
  name: ogbg-molpcba
  task: graph
  task_type: classification_multilabel
  transductive: False
  node_encoder: True
  node_encoder_name: LinearNode+GraphormerBias
  node_encoder_bn: False
  edge_encoder: True
  edge_encoder_name: Bond
  edge_encoder_bn: False
posenc_GraphormerBias:
  enable: True
  num_spatial_types: 20
  num_in_degrees: 9
  num_out_degrees: 94
# posenc_HIG:
#   enable: False
#   loss : 1.0
#   nodes_interpolated: 2
#   minimum_node_size: 10
# train:
#   mode: custom
#   batch_size: 512
#   eval_period: 1
#   ckpt_period: 100
train:
  mode: custom
  sampler: full_batch
  eval_period: 5
  enable_ckpt: False
model:
  type: Graphormer
  loss_fun: cross_entropy
  edge_decoding: dot
graphormer:
  use_graph_token: False
  num_layers: 2
  num_heads: 4
  embed_dim: 64  # `graphormer.embed_dim` must match `gnn.dim_inner`
  dropout: 0.2
  attention_dropout: 0.0
  mlp_dropout: 0.2
  input_dropout: 0.0
gnn:
  head: default  # san_graph
  layers_pre_mp: 0
  layers_post_mp: 1  # Not used when `gnn.head: san_graph`
  dim_inner: 64  # `gt.dim_hidden` must match `gnn.dim_inner`
  batchnorm: True
  act: relu
  dropout: 0.2
  agg: mean
  normalize_adj: False
optim:
  batch_accumulation: 1
  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 1e-5
  base_lr: 0.0005
  max_epoch: 100
  scheduler: cosine_with_warmup
  num_warmup_epochs: 10
